### ISSUE TITLE
order details are differnent in step3 with that in step4

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#102]
1. create an order and pick aircraft chanllenger 605 with 9 days
2. in step 3, pilot rate is 1260, 9 days
3.in step 4, pilot rate is 1320, 8 days, total price varied too.
![189516167536324654](https://user-images.githubusercontent.com/33741789/34029552-259d6a22-e1a4-11e7-93c2-566572f9caca.jpg)
![650541199430799491](https://user-images.githubusercontent.com/33741789/34029556-2948273e-e1a4-11e7-85c9-66db86aef6f9.jpg)

**Comment by Mobiusor** [comment]
fixed
