### ISSUE TITLE
pilot没有设置头像时，不显示aerolink默认pilot头像

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#103]
pilot web:
![d9b36af2f5d777ccd386492a751081e](https://user-images.githubusercontent.com/33741789/34029670-b6c55ab4-e1a4-11e7-8406-ebfc263db3cd.png)
pilot app:
![900173664351447952](https://user-images.githubusercontent.com/33741789/34030321-591fc266-e1a7-11e7-844a-c73bb1626e3c.jpg)

**Comment by Mobiusor** [comment]
不能用web这个头像，我们跟designer统一要了一个类似的占位符
