### ISSUE TITLE
order 也不显示order，在calendar里有2个in 30 days order

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#105]
![794142503873428529](https://user-images.githubusercontent.com/33741789/34035146-0ef1152c-e1bc-11e7-82c2-089e197050c7.jpg)
![517118700531174176](https://user-images.githubusercontent.com/33741789/34035149-1071ce64-e1bc-11e7-9f5a-5483784191b4.jpg)

**Comment by Mobiusor** [comment]
create order issue, has fixed, no duplicated order will be made
