### ISSUE TITLE
mismatch between UI proposal and real page

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#108]
![bd795c509ee19409f495b1fd6c8c799](https://user-images.githubusercontent.com/33741789/34189585-266bb6bc-e577-11e7-8697-7ad2d0c1999d.png)

**Comment by licetus** [comment]
![image](https://user-images.githubusercontent.com/22375749/34191055-3c19fb10-e57f-11e7-8d7b-f5037b8ee100.png)
original design in mock is unreasonable

**Comment by boeingpiggy** [comment]
Please change the color of the step which has alreadly been passed to black instead of grey. Grey makes users feel it's disabled.

**Comment by licetus** [comment]
fixed, pls check
