### ISSUE TITLE
order confirmation page mismatch between proposal and real UI

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#109]
![9f4aa694618c34607bf6416b4bcb440](https://user-images.githubusercontent.com/33741789/34189660-8b49137c-e577-11e7-9cab-6b52a8daad57.png)

**Comment by licetus** [comment]
![image](https://user-images.githubusercontent.com/22375749/34191090-6a8cd670-e57f-11e7-9205-9350024b0a26.png)

**Comment by boeingpiggy** [comment]
For aircraft type, we might need to provide the brand name + type name.

**Comment by licetus** [comment]
fixed, pls check

**Comment by Jean2099** [comment]
please also fix basic info in step 2

**Comment by licetus** [comment]
step 2 is an other compontent
