### ISSUE TITLE
operator UI mismatch check

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#110]
![11a706228d16f973c1cfa0a458cf352](https://user-images.githubusercontent.com/33741789/34189703-c7d9ad74-e577-11e7-881b-5a433c87e0b9.png)

**Comment by licetus** [comment]
International experience is removed

**Comment by boeingpiggy** [comment]
Yup, I remember it's been removed. But for the position of the nationality is wrong.

**Comment by tianjilanfeng** [comment]
yes. need to change the position and fond, size

**Comment by licetus** [comment]
fixed, pls check
