### ISSUE TITLE
pilot documents显示不正确，且多余3个的doc只显示一个

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#111]
1. Certificate ‘’Unkonw‘’ need to fix
2. please discuss with related team member if provide details view of document
![60d9f5702342480056a0ac6028798c9](https://user-images.githubusercontent.com/33741789/34190202-6d942850-e57a-11e7-9d40-037ba231f22f.png)

**Comment by licetus** [comment]
fixed, pls check
