### ISSUE TITLE
order list 里的结束日期和order detail里的结束日期不一致

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#114]
![802627926262088179](https://user-images.githubusercontent.com/33741789/34243595-71effa4a-e65c-11e7-93c1-0db535f358f7.jpg)
![557097944520899610](https://user-images.githubusercontent.com/33741789/34243597-72862eb6-e65c-11e7-83ca-89bb6256d128.jpg)

**Comment by Mobiusor** [comment]
fixed
