### ISSUE TITLE
pilot rate显示不正确

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#115]
选择challenger 605，无论是2天的order还是大约30天的order，rate都是892.5，还没有计算aerolink rate
![6320e1ad6c6bfb25425f90a37734f99](https://user-images.githubusercontent.com/33741789/34243657-c5a5df92-e65c-11e7-99b6-7b8770729779.png)

**Comment by Jean2099** [comment]
![189511447475977962](https://user-images.githubusercontent.com/33741789/34243678-d95ef06e-e65c-11e7-988a-a0358b9abe4f.jpg)

**Comment by Mobiusor** [comment]
removed fraction digits, add wording "from" to align website design.
