### ISSUE TITLE
输入message后，点聊天消息框空白处，出现键盘退出后出现白色部分

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#116]
![348592643196274783](https://user-images.githubusercontent.com/33741789/34244250-5fb8ed0c-e65f-11e7-9152-1d356c669eaa.jpg)

**Comment by Jean2099** [comment]
重新截图，让白色部分看清楚
![d48e84883294aad36936970c8194544](https://user-images.githubusercontent.com/33741789/34244290-96c088d2-e65f-11e7-9901-f43f4d9d7543.png)

**Comment by Jean2099** [comment]
no 100% repro

**Comment by Mobiusor** [comment]
cannot repro, will fix in V2
