### ISSUE TITLE
Please confirm the IME api is right for 3.1 

### ISSUE THREAD

**Issue by tianjilanfeng** [Mobiusor/aerolink-issue#12]
![image](https://user-images.githubusercontent.com/33724989/33081541-910ba66c-cf15-11e7-8ca6-bf6ecbb286b0.png)

**Comment by Mobiusor** [comment]
fixed

**Comment by tianjilanfeng** [comment]
点完send怎么总是键盘弹回去，还得再次点击输入。别让弹回去！

**Comment by Mobiusor** [comment]
fixed

**Comment by tianjilanfeng** [comment]
Done
