### ISSUE TITLE
reg.country显示不一致在pilot app和operator app上

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#120]
![590394759099798792](https://user-images.githubusercontent.com/33741789/34332012-fdc71582-e966-11e7-9c50-7e66ad8f8f1c.jpg)
![582201426031458180](https://user-images.githubusercontent.com/33741789/34332014-ff1ab650-e966-11e7-9588-739eca525362.jpg)

**Comment by Mobiusor** [comment]
fixed

**Comment by Mobiusor** [comment]
use format as "United States of America (N)" in both apps
