### ISSUE TITLE
total price doesn't equal to daily rate*days*(1-discount)

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#123]
1366*56*0.85=65021.6, it should display 65021

**Comment by Jean2099** [comment]
￼
![wechatimg7](https://user-images.githubusercontent.com/33741789/34343137-f8a192b4-e9ff-11e7-92f9-950457852b2b.jpeg)
￼

**Comment by Mobiusor** [comment]
by design, price has been rounded, the actual pilot daily rate is 1366.xx
