### ISSUE TITLE
view pilot， certs显示不正确，放大图片不显示在最前面

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#124]
pilot name：Javier Alexander； aerolink ID：AL-4
1. view pilot，certs显示默认图片
2.pilot 有blur copy，但是没有显示
3. passport显示成FAA
4. 放大图片显示在弹出页面后端
5. order confirm后只有一个cert显示，pilot一共有4个certs

![order confirm-missing certs](https://user-images.githubusercontent.com/33741789/34343218-a5af007a-ea02-11e7-82ab-60a810105df0.jpeg)
![passport](https://user-images.githubusercontent.com/33741789/34343232-037d7baa-ea03-11e7-86d7-1d737b128511.jpeg)
![view detail page-background](https://user-images.githubusercontent.com/33741789/34343233-09d3ffe2-ea03-11e7-82d6-a94ced7c3780.jpeg)
![wrong passport](https://user-images.githubusercontent.com/33741789/34343235-1497c6e8-ea03-11e7-980c-9eda744856c0.jpeg)

**Comment by licetus** [comment]
fixed, pls check
