### ISSUE TITLE
The pop up IME table type is wrong in EMP and remark context

### ISSUE THREAD

**Issue by tianjilanfeng** [Mobiusor/aerolink-issue#15]
it should be words and number. current is just only can input number.

![image](https://user-images.githubusercontent.com/33724989/33082183-1b3af65c-cf17-11e7-90c5-ddf12a78d19d.png)
![image](https://user-images.githubusercontent.com/33724989/33082264-4d6e59c0-cf17-11e7-8a35-87eb6f8b969b.png)

**Comment by Mobiusor** [comment]
fixed

**Comment by tianjilanfeng** [comment]
same issue when input place of birth
![618996512004341412](https://user-images.githubusercontent.com/33724989/33131008-31575796-cfd0-11e7-9ede-5581e760b5d7.jpg)

**Comment by tianjilanfeng** [comment]
same issue when input place of birth in this passport page
![589255557860265671](https://user-images.githubusercontent.com/33724989/33131037-4a8c3aa6-cfd0-11e7-8600-a941d63bfe0e.jpg)

**Comment by Mobiusor** [comment]
fixed

**Comment by tianjilanfeng** [comment]
done
