### ISSUE TITLE
Health will give a 3 levels roll bar instead current behavior

### ISSUE THREAD

**Issue by tianjilanfeng** [Mobiusor/aerolink-issue#17]
Health should be **1st Class Medial**, **2nd Class Medical** or **3rd Class Medical** 

![image](https://user-images.githubusercontent.com/33724989/33082658-449c1426-cf18-11e7-83e3-eff9e304e2e6.png)

**Comment by Mobiusor** [comment]
fixed

**Comment by tianjilanfeng** [comment]
Closed
