### ISSUE TITLE
Instead of “CERTIFICATE” should change to “LICENSE“ 

### ISSUE THREAD

**Issue by tianjilanfeng** [Mobiusor/aerolink-issue#18]
![image](https://user-images.githubusercontent.com/33724989/33082761-82c5b32e-cf18-11e7-8f9f-e1d1d3bd4137.png)

**Comment by Mobiusor** [comment]
fixed

**Comment by tianjilanfeng** [comment]
这个title 还没改
![207093918016166274](https://user-images.githubusercontent.com/33724989/33130879-b9b1b862-cfcf-11e7-8118-7c01b2d474dc.jpg)

**Comment by Mobiusor** [comment]
ok，改了

**Comment by tianjilanfeng** [comment]
Done
