### ISSUE TITLE
Create order: no pilot lists, no information/suggestion to user

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#20]
resolution: 显示no available pilot during the period, please contact aerolink via phone call or massage
![e8ec166e6acb58e93ebc26fe88567fe](https://user-images.githubusercontent.com/33741789/33107626-121e920c-cf73-11e7-88a8-7f3716088ba8.png)

**Comment by licetus** [comment]
fixed, show "no available pilot during the period, please contact aerolink via phone call or massage" and contact button

**Comment by Jean2099** [comment]
it remains empty list without any messaging, is it due to the operator hasn't create a profile, cause it is saying **GetOperatorProfile error**

**Comment by licetus** [comment]
这个是正常的，如果operator有profile的时候没问题了就把这个isuue关了，重新提交一个need GetOperatorProfile error handler 的issue

**Comment by Jean2099** [comment]
no order..., 是否需要写No order。。。？

**Comment by licetus** [comment]
没有profile会直接跳转到profile页面，不在这个页面停留
