### ISSUE TITLE
输入完了，但是仍然需要输入，由于这个问题profile 在admin端修改后不能保存

### ISSUE THREAD

**Issue by tianjilanfeng** [Mobiusor/aerolink-issue#27]
还有pilot rate 价格计算有问题，算出来的价格是0
![206080415646884697](https://user-images.githubusercontent.com/33724989/33132213-f17a5354-cfd3-11e7-950c-232cf2bc38ab.jpg)

**Comment by licetus** [comment]
fixed, form validator rule error, set pilot rate default 1, pls check

**Comment by tianjilanfeng** [comment]
can't verify now, due to can't get the pilot info in the admin web site

**Comment by tianjilanfeng** [comment]
closed
