### ISSUE TITLE
when create passport in pilot app, error: dateof birth must be larger than or equal to 0

### ISSUE THREAD

**Issue by tianjilanfeng** [Mobiusor/aerolink-issue#32]
i input the right DOB, but still show this error, which lead to unsuccessfully create passport

**Comment by Mobiusor** [comment]
how to repro this bug? what's the DOB value you input

**Comment by Jean2099** [comment]
输入一个1966年的出生日期就会出现这样的error

**Comment by tianjilanfeng** [comment]
give a case::
![203314516936253298](https://user-images.githubusercontent.com/33724989/33804180-8d27d088-ddda-11e7-9a0a-dfcd50824c6d.jpg)
![717306475444879377](https://user-images.githubusercontent.com/33724989/33804182-8f8f7c0e-ddda-11e7-8b46-426213c30916.jpg)

**Comment by tianjilanfeng** [comment]
这个要赶紧fix了呀！

**Comment by Mobiusor** [comment]
fixed

**Comment by tianjilanfeng** [comment]
Done
