### ISSUE TITLE
order active message 页面显示问题

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#40]
1. pilot 图片显示成默认图片而不是pilot端设置的
2. message 框下的load more，点了变会后一直load more 灰色
3. 右侧的是operator头像没有加载么，需要设置默认图标么
![image](https://user-images.githubusercontent.com/33741789/33195213-b7bad0a6-d110-11e7-8516-b9b8be0db6df.png)

**Comment by licetus** [comment]
1、3 fixed
2: load more在加载完所有历史消息后会disable，正常
