### ISSUE TITLE
add pilot failed in admin portal with "invalid verify code"

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#42]
![fb6faaa288bba7b17a4296b6588da1b](https://user-images.githubusercontent.com/33741789/33362664-774e0f04-d518-11e7-8824-26a2482847d4.png)

**Comment by licetus** [comment]
1.error message error
2.international mobile number could be string

**Comment by Mobiusor** [comment]
fixed

**Comment by Jean2099** [comment]
it remains, 如果输入string 类型的account 还是显示invalid verify code
