### ISSUE TITLE
添加documents选择type certificate，直接点默认选项，type栏不会显示

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#43]
直接选择默认选项，没法选择
需要滚动选择其它选项，再滚动点回certificate，上面type栏才会正确显示第一个默认的certificate，在app的其它滚动条选择时，也存在同样问题

**Comment by Mobiusor** [comment]
fix了所有的除了日期的滚动选择

**Comment by Jean2099** [comment]
certificate还是不能直接点击选择

**Comment by Mobiusor** [comment]
fixed
