### ISSUE TITLE
"New Aircraft" leads user confuse  in Admin Portal when add pilot aircraft licence

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#45]
在admin 端创建pilot时候：
![569f6ea65452dd60e72937b33d79560](https://user-images.githubusercontent.com/33741789/33466465-321dfa6c-d689-11e7-9273-0fba8ffc6747.png)
但是在pilot app里却是aircraft licence
![475218675650428935](https://user-images.githubusercontent.com/33741789/33466484-4de2449c-d689-11e7-923d-d14f375e6edb.jpg)
需要确认wording

**Comment by tianjilanfeng** [comment]
Please change "New Aircraft" to "Add Aircraft License"

**Comment by licetus** [comment]
fixed, pls check

**Comment by tianjilanfeng** [comment]
Done
