### ISSUE TITLE
calendar没有随日期变动而整月高亮

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#47]
现在是12月份，转到calendar，12月1日不是高亮的
![430245697018367788](https://user-images.githubusercontent.com/33741789/33469027-373e8cde-d69b-11e7-8fb6-b6ac2c2e090f.jpg)

**Comment by Mobiusor** [comment]
没有太明白这个高亮是什么意思 期望结果是什么？
