### ISSUE TITLE
Message Across: admin输入信息，在pilot app端显示成operator的输入

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#48]
1. admin portal点开已有order-》messages
2. 输入信息：what should I say
3. operator web端显示正常
4. pilot app端查看信息，显示operator输入的what should I say，至少显示图片是operator
for 2：
![f1a2eb73fb6972b15c91174bb9261c6](https://user-images.githubusercontent.com/33741789/33471641-4d0e7606-d6a9-11e7-8802-b954dd2f2c35.png)
for 4： Hellen：operator
![190065604552117944](https://user-images.githubusercontent.com/33741789/33471649-56e1eba4-d6a9-11e7-8105-19c9af681bfb.jpg)
![843032057710148768](https://user-images.githubusercontent.com/33741789/33471652-581a26a8-d6a9-11e7-860f-28870a4147ab.jpg)

**Comment by Mobiusor** [comment]
fixed

**Comment by Jean2099** [comment]
聊天框里的消息头像显示fix了，但是message 列表里的聊天如果最新消息是aerolink发送的，头像和显示名仍然是为operator，是否和最初发送消息为operator有关

**Comment by Mobiusor** [comment]
By design, message列表里用operator的头像来表示对应的order
