### ISSUE TITLE
非super admin 的头像显示

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#49]
super admin在message显示aero link图标
非super admin： aerolink-ss，头像是否显示aerolink
![2a1c885f530e733d8f9bc8127e82952](https://user-images.githubusercontent.com/33741789/33471841-1c7100e4-d6aa-11e7-8f4e-48d50dc9f87c.png)

**Comment by licetus** [comment]
右边是operator的头像，其他人的头像在左边
