### ISSUE TITLE
pilot documents, scanned copy 不能放大

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#50]
![6ae0a731d01ab5f7ee4c717568ec1cf](https://user-images.githubusercontent.com/33741789/33473918-582787c6-d6b3-11e7-9b21-5daad440c79e.png)

**Comment by licetus** [comment]
这里design的时候没有接到需要放大的feature，可能确实需要增加一个

**Comment by Jean2099** [comment]
看见增加了view Detail
