### ISSUE TITLE
order page显示异常

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#54]
1. pilot 头像显示不正常
2. view Details button不显眼，找了好久才知道那个是能看detail
3. start a convertion 和Active紧紧相连了
4. Active的绿色背景容易让人去点击，这个tag是否需要重新设计
![c3e4ee542e97510743b558c99edecaa](https://user-images.githubusercontent.com/33741789/33645020-9a0806ce-da83-11e7-890d-db037bebd7b7.png)

**Comment by licetus** [comment]
fixed, pls check
