### ISSUE TITLE
select pilot页面pilot photo处理不够gracely，似乎是放大又截取头像了

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#55]
![e499dde7deb6934827ff6ce4ce41956](https://user-images.githubusercontent.com/33741789/33645105-19899b7e-da84-11e7-96d2-668561782087.png)

**Comment by licetus** [comment]
正常情况，请admin和pilot上传头像时注意尺寸，没有人脸识别功能

**Comment by Jean2099** [comment]
这是等比例缩放么还是只截取某一篇区域，是否在pilot和admin 上传photo时候做限制，这样好处理一些

**Comment by licetus** [comment]
这个处理起来很复杂，暂时不做这个吧
