### ISSUE TITLE
create order failed 

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#56]
![ef65945ad67497c4adfb3ee50e1ba25](https://user-images.githubusercontent.com/33741789/33645135-3b9a5abe-da84-11e7-95dd-2b16496b0aea.png)

**Comment by licetus** [comment]
请详细说明操作过程

**Comment by licetus** [comment]
查明原因，pilot没有设置rate，这是之前pilot rate没有default值的遗留问题，已经解决
