### ISSUE TITLE
admin message 数字什么意思

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#57]
![2fa6505b41b5e598ece08b4ccbe5940](https://user-images.githubusercontent.com/33741789/33645276-e20f1c68-da84-11e7-8c0b-02b7b2d82722.png)

![80d31492db43fb70a1adf2ff2c7322c](https://user-images.githubusercontent.com/33741789/33645197-96cfbe38-da84-11e7-909f-e92f54eb0091.png)

**Comment by licetus** [comment]
breadcrumb is updated, pls check
