### ISSUE TITLE
Contact Support->Leave a Message 点击没反应

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#58]
![306c86fd8e7e5e197fa60a78b259ee1](https://user-images.githubusercontent.com/33741789/33650382-bc98d326-da9c-11e7-94cc-1cca17aca4d3.png)

**Comment by licetus** [comment]
请详细说明操作流程

**Comment by Jean2099** [comment]
点击此页面上的Leave a message，没有跳转到message chat window

**Comment by licetus** [comment]
未能重现这个bug， 可能是由于operator profile 非法引起的

**Comment by Jean2099** [comment]
打开和pilot聊天的order activated页面，再点击contact support，leave a message will not trigger messages to aerolink。 please contact me if it doesn't repro on your side

**Comment by licetus** [comment]
fixed
