### ISSUE TITLE
Notification: 没有未读消息时，有红点提示

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#59]
![eb0d72ae3507450e902f6dace1d9d7d](https://user-images.githubusercontent.com/33741789/33650473-1c61d6a4-da9d-11e7-906c-7f0680fe8110.png)

**Comment by licetus** [comment]
hasNew = true but no content

**Comment by licetus** [comment]
未能重现这个问题， 可能是服务器延迟引起的

**Comment by Jean2099** [comment]
刷新整个页面，红点还是存在
