### ISSUE TITLE
Total price formula change and format change

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#62]
![bd483d5650a68ca0406cffbe8083877](https://user-images.githubusercontent.com/33741789/33696038-4f031cfa-db3b-11e7-8cbb-83a8d75738af.png)

**Comment by Jean2099** [comment]
also comments 4.5

**Comment by licetus** [comment]
need to confirm

**Comment by licetus** [comment]
updated, pls check

**Comment by Jean2099** [comment]
no total price before discount

**Comment by tianjilanfeng** [comment]
Please fix it as the high priority bug!

**Comment by licetus** [comment]
fixed, pls check
