### ISSUE TITLE
need to handle order confirmation page 

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#65]
9.1 & 9.2
![44fa3f147cb67477b3dae4bbac5c13d](https://user-images.githubusercontent.com/33741789/33697381-9887c942-db41-11e7-86f4-4641e180d09c.png)

**Comment by Jean2099** [comment]
还有个wording 问题 ，第一个蓝色连接里的“condition”写错了

**Comment by licetus** [comment]
fixed， pls check
