### ISSUE TITLE
admin portal Dashboard具体功能，何时完成

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#67]
![f30d04a07e4c929231b3e9cabb10a2d](https://user-images.githubusercontent.com/33741789/33706142-10450734-db6e-11e7-8812-531f7ac93522.png)

**Comment by licetus** [comment]
没有dashboard， 这是项目初创时遗留的框架，已经移除

**Comment by Jean2099** [comment]
verified
