### ISSUE TITLE
Change Avatar to Profile Photo- admin profile

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#70]
![56188990f2f4e2439f283c341f41ed2](https://user-images.githubusercontent.com/33741789/33706851-60c2372a-db70-11e7-9b55-9554b998e9bd.png)

**Comment by Jean2099** [comment]
same with operator profile change "Avatar" too

**Comment by licetus** [comment]
updated, pls check

**Comment by Jean2099** [comment]
Admin portal and operator web->modify my profile, it remains "Change My Avatar"

**Comment by licetus** [comment]
图上指示的只有admin的operator profile，其他地方未处理
