### ISSUE TITLE
高亮或加重处理aircraft，以使用户可以第一眼看到aircraft可以点开编辑

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#71]
14.1
![fa20c7da66f095f5820af548479b3cb](https://user-images.githubusercontent.com/33741789/33707730-6233db10-db73-11e7-9d7c-449c10760663.png)

**Comment by licetus** [comment]
1.  updated, now you can click table row to open modify modal
2.  these are test data, real data input is admin's work.
3. aricraft list should modify database, can not modify in this page

**Comment by Jean2099** [comment]
verified
