### ISSUE TITLE
添加第二个blur copy时，upload image仍然显示第一个blur copy， 需要设置默认图片

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#72]
![98a2af2d3a9c7620b1f5f017a5a72f6](https://user-images.githubusercontent.com/33741789/33708163-a7310430-db74-11e7-99d1-a913be7d01af.png)

**Comment by licetus** [comment]
fixed, pls check

**Comment by Jean2099** [comment]
verified
