### ISSUE TITLE
add back button to messages list

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#73]
![9b4530a91352a40c0e56e1c3819a515](https://user-images.githubusercontent.com/33741789/33708303-07f1d786-db75-11e7-8283-331759f0d1bb.png)

**Comment by licetus** [comment]
1. you can click back button in explorer or click breadcrumb to back to messages page, i think it is not necessary to add another back button
2. breadcrumb is updated, pls check
