### ISSUE TITLE
Under Notification, Messages(1), no response after click "Order Activated"

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#74]
orderActivated and "Order 100004 has been activated" are clickable but no response after click
是否要在点击后真正跳转到对应message页面或者不显示可以点击
![3ed14dd5654e0277190eceba6bbb077](https://user-images.githubusercontent.com/33741789/33750552-ae332ba0-dc0f-11e7-8ad4-2c672e2f606a.png)

**Comment by licetus** [comment]
未能重现这个bug，可能是因为pilot profile非法引起的
