### ISSUE TITLE
为啥没信息的时候也show红点呀？点进去又一直在load，不出内容。

### ISSUE THREAD

**Issue by tianjilanfeng** [Mobiusor/aerolink-issue#78]
![image](https://user-images.githubusercontent.com/33724989/33804245-df71e6f2-dddb-11e7-87b3-a970fb6cdafc.png)
![714893012214810318](https://user-images.githubusercontent.com/33724989/33804250-e989f292-dddb-11e7-9f8c-2c02916a0858.jpg)
![504081998753950129](https://user-images.githubusercontent.com/33724989/33804251-ead5ea48-dddb-11e7-920d-5fb69f08f320.jpg)

**Comment by licetus** [comment]
fixed, pls check

**Comment by tianjilanfeng** [comment]
Done
