### ISSUE TITLE
请把operator profile 页面的discount rate 去掉，Aerolink不希望user看到这个。

### ISSUE THREAD

**Issue by tianjilanfeng** [Mobiusor/aerolink-issue#79]
![image](https://user-images.githubusercontent.com/33724989/33804834-4cdc1c06-dde8-11e7-9bdb-0e68f225fb12.png)

**Comment by licetus** [comment]
周五已有结果，100%时不显示，小于100%时显示 - x%，pls check

**Comment by tianjilanfeng** [comment]
小手挺快呀！刚才我看100%还显示呢！！！
