### ISSUE TITLE
添加aircraft licence，不设置start date和enddate保存时error提示不合理

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#81]
1. 不添加必需的日期直接保存提示信息如下
2. 弹出提示后返回到licence 页面，应该停留在添加licence页面让用户继续添加日期
![767822476815544766](https://user-images.githubusercontent.com/33741789/33823710-020150f2-de97-11e7-95ec-38c32fdab363.jpg)

**Comment by Mobiusor** [comment]
fixed
