### ISSUE TITLE
添加aircraft licence，end date小于start date，也可以添加成功

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#82]
下图有2个bug
1. 添加aircraft licence，end date小于start date，也可以添加成功
2. 点击Save，一时没有反应，多点了一次，结果生成两个同样的licence
![562659234592865508](https://user-images.githubusercontent.com/33741789/33823878-8ef34b1e-de97-11e7-9edc-0f8795db9ef0.jpg)

**Comment by Mobiusor** [comment]
fixed
