### ISSUE TITLE
order list时间为12/03-12/10， order detail时间为12/03-12/09，时间不一致

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#88]
![267d6d1ff4547a442aa7867c4d80427](https://user-images.githubusercontent.com/33741789/33928024-49a7549a-e01f-11e7-9263-2c201e71d24e.png)
![d4c342f1915da25db56dd788e87a2e9](https://user-images.githubusercontent.com/33741789/33928045-5af73224-e01f-11e7-83a1-7d1d0167ee23.png)
，

**Comment by Mobiusor** [comment]
fixed
