### ISSUE TITLE
When scroll in the profile page to extend page, the title bar doesn't move

### ISSUE THREAD

**Issue by tianjilanfeng** [Mobiusor/aerolink-issue#9]
![207093918016166274](https://user-images.githubusercontent.com/33724989/33081213-b8c83e32-cf14-11e7-84f1-8a103fd20dcc.jpg)

**Comment by Mobiusor** [comment]
fixed

**Comment by tianjilanfeng** [comment]
Done，虽然滚动的不是很流畅！
