### ISSUE TITLE
录入公司信息后，保存，但是显示不出来

### ISSUE THREAD

**Issue by tianjilanfeng** [Mobiusor/aerolink-issue#91]
在pilot profile 页面的Employement History， 添加公司名称，但是保存后网页中没有显示

**Comment by Mobiusor** [comment]
我这里无法重现， 试了一遍是好的，你再看看？

**Comment by tianjilanfeng** [comment]
还是显示不出来。我这上传不了图。图发群里了

**Comment by tianjilanfeng** [comment]
Done，fix之后，mark一下，我都知道是咋回事就打回来了
